name: QA API Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # 매일 오전 9시 (UTC)에 자동 실행
    - cron: '0 9 * * *'
  workflow_dispatch:
    # 수동 실행 가능

permissions:
  contents: read
  security-events: write
  checks: write
  pages: write # GitHub Pages 배포를 위해 추가
  id-token: write # GitHub Pages 배포를 위해 추가

jobs:
  # 코드 품질 검사
  lint-and-format:
    runs-on: ubuntu-latest
    name: Code Quality Check

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5 # v4 -> v5로 업데이트
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # E501: line too long 에러는 무시 (--ignore=E501)
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --ignore=E501,W503 --exit-zero --max-complexity=10 --max-line-length=88 --statistics

    - name: Check import sorting
      run: |
        isort --check-only --diff .

    - name: Check code formatting
      run: |
        black --check --diff .